# Generated by Django 4.1.6 on 2023-02-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='whattodo',
            new_name='title',
        ),
    ]
